services:
  - type: web
    name: bajaj-api-round-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: USE_MEMORY_DB
        value: "false"
